CREATE TABLE Alumnos (
	id INT NOT NULL AUTO_INCREMENT UNIQUE,
	dni INT NOT NULL PRIMARY KEY,
	nombre VARCHAR(90) NOT NULL,
	apellido VARCHAR(90) NOT NULL,
	fechaNac DATE NOT NULL,
	telefono VARCHAR(90),
	direccion VARCHAR(90)
);